# 새로운 노래
* 전 주에 없던 새로운 노래 확인

## 라이브러리

In [2]:
import pandas as pd
import os

## 코드 현재 경로

In [3]:
code_path = os.getcwd().replace('\\', '/')
code_path

'c:/data/Wantreez/Crawling/music'

## 사이트 설정

In [4]:
# 파일 불러오기
site_name = 'bugs'
folder_path = f'/crawled_data/mod_{site_name}/'
path = code_path + folder_path
try:
    os.chdir(path)
except:
    pass

In [5]:
# 파일 이름들
file_list = os.listdir()
file_list

['live_bugs_20220422_105549.xlsx',
 'live_bugs_20220425_110806.xlsx',
 'live_bugs_20220426_110837.xlsx',
 'live_bugs_20220427_110836.xlsx',
 'live_bugs_20220428_110800.xlsx',
 'live_bugs_20220429_110800.xlsx',
 'live_bugs_20220430_110800.xlsx',
 'live_bugs_20220501_110800.xlsx',
 'live_bugs_20220502_110800.xlsx',
 'live_bugs_20220503_110800.xlsx',
 'live_bugs_20220504_110800.xlsx',
 'live_bugs_20220505_110800.xlsx',
 'live_bugs_20220506_110800.xlsx',
 'live_bugs_20220507_110800.xlsx',
 'live_bugs_20220508_110800.xlsx',
 'live_bugs_20220509_110800.xlsx',
 'live_bugs_20220510_110800.xlsx']

## 시간 설정

In [6]:
# 전 주 파일 날짜
start_date = '2022-04-25'
end_date = '2022-05-01'

In [7]:
# 비교할 파일 날짜(일주일)
new_start_date = '2022-05-02'
new_end_date = '2022-05-08'
new_dates_df = pd.date_range(new_start_date, new_end_date).astype(str)
new_dates_df

Index(['2022-05-02', '2022-05-03', '2022-05-04', '2022-05-05', '2022-05-06',
       '2022-05-07', '2022-05-08'],
      dtype='object')

In [8]:
for new_one_date in new_dates_df:
    print(new_one_date)

2022-05-02
2022-05-03
2022-05-04
2022-05-05
2022-05-06
2022-05-07
2022-05-08

In [9]:
# 전체 df 생성
total_df = pd.DataFrame()
for one in file_list:
    temp = pd.read_excel(one)
    total_df = pd.concat([total_df, temp], ignore_index=True)
total_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1700 entries, 0 to 1699
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사이트     1700 non-null   object
 1   날짜      1700 non-null   object
 2   순위      1700 non-null   int64
 3   곡       1700 non-null   object
 4   가수      1700 non-null   object
 5   앨범      1700 non-null   object
 6   소속사     1652 non-null   object
 7   소속사_분류  1652 non-null   object
dtypes: int64(1), object(7)
memory usage: 106.4+ KB

In [10]:
total_df['날짜'] = total_df['날짜'].astype(str)

In [11]:
before_df = total_df[ (total_df['날짜'] >= start_date) & (total_df['날짜'] <= end_date)].reset_index(drop=True)
before_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사이트     700 non-null    object
 1   날짜      700 non-null    object
 2   순위      700 non-null    int64
 3   곡       700 non-null    object
 4   가수      700 non-null    object
 5   앨범      700 non-null    object
 6   소속사     698 non-null    object
 7   소속사_분류  698 non-null    object
dtypes: int64(1), object(7)
memory usage: 43.9+ KB

In [12]:
new_df = total_df[ (total_df['날짜'] >= new_start_date) & (total_df['날짜'] <= new_end_date)].reset_index(drop=True)
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사이트     700 non-null    object
 1   날짜      700 non-null    object
 2   순위      700 non-null    int64
 3   곡       700 non-null    object
 4   가수      700 non-null    object
 5   앨범      700 non-null    object
 6   소속사     700 non-null    object
 7   소속사_분류  700 non-null    object
dtypes: int64(1), object(7)
memory usage: 43.9+ KB

## 1주일 동안 새로 진입한 곡 추출

In [183]:
title_list = df['곡'].unique()
title_list[:5]

array(['LOVE DIVE', '봄 to 러브', 'Seoul', 'TOMBOY', '봄여름가을겨울 (Still Life)'],
      dtype=object)

In [185]:
pop_title_list = []
pop_artist_list = []
pop_date_df = pd.DataFrame()
for new_one_date in new_dates_df:
    new_date_df = total_df[total_df['날짜'] == new_one_date].reset_index(drop=True)

    for i in range(new_date_df.shape[0]):
        one_title = new_date_df['곡'][i]
        one_artist = new_date_df['가수'][i]
        if one_title not in title_list:
            pop_title_list.append(one_title)
            pop_artist_list.append(one_artist)
    print(new_one_date)
    print( len(pop_title_list), len(pop_artist_list) )

    for two_title, two_artist in zip(pop_title_list, pop_artist_list):
        temp = new_df[ (new_df['곡'] == two_title) & (new_df['가수'] == two_artist)]
        pop_date_df = pd.concat([pop_date_df, temp], ignore_index=True)
        pop_date_df = pop_date_df.drop_duplicates(['날짜', '곡', '가수'], ignore_index=True)

2022-05-02
8 8
2022-05-03
26 26
2022-05-04
44 44
2022-05-05
64 64
2022-05-06
84 84
2022-05-07
103 103
2022-05-08
120 120

In [187]:
pop_date_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사이트     120 non-null    object
 1   날짜      120 non-null    object
 2   순위      120 non-null    int64
 3   곡       120 non-null    object
 4   가수      120 non-null    object
 5   앨범      120 non-null    object
 6   소속사     120 non-null    object
 7   소속사_분류  120 non-null    object
dtypes: int64(1), object(7)
memory usage: 7.6+ KB

In [188]:
pop_date_df.head()

    사이트          날짜  순위            곡       가수                  앨범   소속사 소속사_분류
0  bugs  2022-05-02  35        나의 봄은      이수현  나의 해방일지 OST Part 7    YG     YG
1  bugs  2022-05-03  37        나의 봄은      이수현  나의 해방일지 OST Part 7    YG     YG
2  bugs  2022-05-07  96        나의 봄은      이수현  나의 해방일지 OST Part 7    YG     YG
3  bugs  2022-05-02  51          잊을께       YB         [YB] Stream  디컴퍼니     기타
4  bugs  2022-05-02  74  Unstoppable  Sia(시아)         Unstoppable    해외     기타

### 새로 진입한 곡의 평균 순위

In [190]:
mean_pop_df = pop_date_df.groupby(['소속사', '곡', '가수']).agg('mean').reset_index()
mean_pop_df

               소속사                    곡                 가수    순위
0              285        Way Back Home          숀 (SHAUN)  86.0
1            ABYSS                   너랑    멜로망스(MeloMance)  89.0
2            ABYSS                   초대    멜로망스(MeloMance)  13.4
3   AMBITION MUSIK  Trip (Feat. Hannah)  릴러말즈 (Leellamarz)  99.0
4   Amoeba Culture               눈에 넣어도                 개코  51.0
..             ...                  ...                ...   ...
64              해외             Memories         Conan Gray  96.0
65              해외         Shape Of You  Ed Sheeran(에드 시런)  93.0
66              해외              Shivers  Ed Sheeran(에드 시런)  70.0
67              해외              Sunroof        Nicky Youre  82.0
68              해외          Unstoppable            Sia(시아)  74.0

[69 rows x 4 columns]

In [191]:
mean_pop_df.columns = ['소속사', '곡', '가수', '순위평균']
mean_pop_df

               소속사                    곡                 가수  순위평균
0              285        Way Back Home          숀 (SHAUN)  86.0
1            ABYSS                   너랑    멜로망스(MeloMance)  89.0
2            ABYSS                   초대    멜로망스(MeloMance)  13.4
3   AMBITION MUSIK  Trip (Feat. Hannah)  릴러말즈 (Leellamarz)  99.0
4   Amoeba Culture               눈에 넣어도                 개코  51.0
..             ...                  ...                ...   ...
64              해외             Memories         Conan Gray  96.0
65              해외         Shape Of You  Ed Sheeran(에드 시런)  93.0
66              해외              Shivers  Ed Sheeran(에드 시런)  70.0
67              해외              Sunroof        Nicky Youre  82.0
68              해외          Unstoppable            Sia(시아)  74.0

[69 rows x 4 columns]

In [192]:
mean_pop_df['순위평균'] = round(mean_pop_df['순위평균'], 1)
mean_pop_df

               소속사                    곡                 가수  순위평균
0              285        Way Back Home          숀 (SHAUN)  86.0
1            ABYSS                   너랑    멜로망스(MeloMance)  89.0
2            ABYSS                   초대    멜로망스(MeloMance)  13.4
3   AMBITION MUSIK  Trip (Feat. Hannah)  릴러말즈 (Leellamarz)  99.0
4   Amoeba Culture               눈에 넣어도                 개코  51.0
..             ...                  ...                ...   ...
64              해외             Memories         Conan Gray  96.0
65              해외         Shape Of You  Ed Sheeran(에드 시런)  93.0
66              해외              Shivers  Ed Sheeran(에드 시런)  70.0
67              해외              Sunroof        Nicky Youre  82.0
68              해외          Unstoppable            Sia(시아)  74.0

[69 rows x 4 columns]

### 파일 저장

In [194]:
# 파일 저장
save_folder = f'/crawled_data/outlier_data/{new_start_date}_{new_end_date}/{site_name}/'
path = code_path + save_folder
mean_pop_df.to_excel(path + f'[{site_name}]{new_start_date}_{new_end_date}_pop_df.xlsx', index=False, encoding='utf-8')

## 1주일 동안 새로 진입한 곡 평균

In [195]:
# 전 주 파일 날짜
start_date = '2022-04-25'
end_date = '2022-05-01'

In [196]:
# 비교할 파일 날짜(일주일)
new_start_date = '2022-05-02'
new_end_date = '2022-05-08'
new_dates_df = pd.date_range(new_start_date, new_end_date).astype(str)

In [198]:
# 음원 사이트
site_list = ['flo', 'bugs', 'genie', 'melon', 'vibe']
for site_name in site_list:
    try:
        folder_path = f'/crawled_data/mod_{site_name}/'
        path = code_path + folder_path
        try:
            os.chdir(path)
        except:
            pass

        # 파일 이름들
        file_list = os.listdir()

        # 전체 df 생성
        total_df = pd.DataFrame()
        for one in file_list:
            temp = pd.read_excel(one)
            total_df = pd.concat([total_df, temp], ignore_index=True)
        total_df['날짜'] = total_df['날짜'].astype(str)

        # 전주, 이번주 df
        before_df = total_df[ (total_df['날짜'] >= start_date) & (total_df['날짜'] <= end_date)].reset_index(drop=True)
        new_df = total_df[ (total_df['날짜'] >= new_start_date) & (total_df['날짜'] <= new_end_date)].reset_index(drop=True)

        # 전주 노래 목록
        title_list = before_df['곡'].unique()
        # 이번주 새로 진입한 곡 df
        pop_title_list = []
        pop_artist_list = []
        pop_date_df = pd.DataFrame()
        for new_one_date in new_dates_df:
            new_date_df = total_df[total_df['날짜'] == new_one_date].reset_index(drop=True)

            for i in range(new_date_df.shape[0]):
                one_title = new_date_df['곡'][i]
                one_artist = new_date_df['가수'][i]
                if one_title not in title_list:
                    pop_title_list.append(one_title)
                    pop_artist_list.append(one_artist)

            for two_title, two_artist in zip(pop_title_list, pop_artist_list):
                temp = new_df[ (new_df['곡'] == two_title) & (new_df['가수'] == two_artist)]
                pop_date_df = pd.concat([pop_date_df, temp], ignore_index=True)
                pop_date_df = pop_date_df.drop_duplicates(['날짜', '곡', '가수'], ignore_index=True)

        # 새로 진입한 곡의 평균
        mean_pop_df = pop_date_df.groupby(['소속사', '곡', '가수']).agg('mean').reset_index()
        mean_pop_df.columns = ['소속사', '곡', '가수', '순위평균']
        mean_pop_df['순위평균'] = round(mean_pop_df['순위평균'], 1)

        # 파일 저장
        save_folder = f'/crawled_data/outlier_data/{new_start_date}_{new_end_date}/{site_name}/'
        path = code_path + save_folder
        os.makedirs(path, exist_ok=True)
        mean_pop_df.to_excel(path + f'[{site_name}]{new_start_date}_{new_end_date}_pop_df.xlsx', index=False, encoding='utf-8')
    except:
        pass

## 10위권 음원의 전주와 이번주 순위 평균 비교

In [28]:
before_top10_df = before_df[before_df['순위'] <= 10]
current_top10_df = new_df[new_df['순위'] <= 10]

In [29]:
before_top10_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70 entries, 0 to 609
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사이트     70 non-null     object
 1   날짜      70 non-null     object
 2   순위      70 non-null     int64
 3   곡       70 non-null     object
 4   가수      70 non-null     object
 5   앨범      70 non-null     object
 6   소속사     70 non-null     object
 7   소속사_분류  70 non-null     object
dtypes: int64(1), object(7)
memory usage: 4.9+ KB

In [30]:
current_top10_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70 entries, 0 to 609
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사이트     70 non-null     object
 1   날짜      70 non-null     object
 2   순위      70 non-null     int64
 3   곡       70 non-null     object
 4   가수      70 non-null     object
 5   앨범      70 non-null     object
 6   소속사     70 non-null     object
 7   소속사_분류  70 non-null     object
dtypes: int64(1), object(7)
memory usage: 4.9+ KB

In [41]:
mean_before_top10_df = before_top10_df.groupby(['사이트', '곡', '가수']).agg('mean').reset_index()
mean_before_top10_df['순위'] = round(mean_before_top10_df['순위'], 1)
mean_before_top10_df.columns = ['사이트', '곡', '가수', '과거순위평균']
mean_before_top10_df.head()

    사이트                     곡                 가수  과거순위평균
0  bugs                 Celeb           싸이 (PSY)     5.0
1  bugs                 Drive       미연 ((여자)아이들)     3.5
2  bugs        Feel My Rhythm  Red Velvet (레드벨벳)     7.5
3  bugs  GANADARA (Feat. 아이유)                박재범    10.0
4  bugs   GANJI (feat. Jessi)           싸이 (PSY)     7.0

In [42]:
mean_current_top10_df = current_top10_df.groupby(['사이트', '곡', '가수']).agg('mean').reset_index()
mean_current_top10_df['순위'] = round(mean_current_top10_df['순위'], 1)
mean_current_top10_df.columns = ['사이트', '곡', '가수', '현재순위평균']
mean_current_top10_df.head()

    사이트               곡                  가수  현재순위평균
0  bugs           Celeb            싸이 (PSY)     6.0
1  bugs        FEARLESS  LE SSERAFIM (르세라핌)     8.3
2  bugs  Feel My Rhythm   Red Velvet (레드벨벳)     7.6
3  bugs       LOVE DIVE           IVE (아이브)     3.0
4  bugs           Seoul              볼빨간사춘기     8.2

In [43]:
bvsc_df = pd.merge(mean_before_top10_df, mean_current_top10_df, on=['곡', '가수'], how='inner')
bvsc_df

,사이트_x,곡,가수,과거순위평균,사이트_y,현재순위평균
0,bugs,Celeb,싸이 (PSY),5.0,bugs,6.0
1,bugs,Feel My Rhythm,Red Velvet (레드벨벳),7.5,bugs,7.6
2,bugs,LOVE DIVE,IVE (아이브),2.3,bugs,3.0
3,bugs,Seoul,볼빨간사춘기,6.6,bugs,8.2
4,bugs,TOMBOY,(여자)아이들,6.4,bugs,5.4
5,bugs,That That (prod. & feat. SUGA of BTS),싸이 (PSY),1.0,bugs,1.0
6,bugs,ZOOM,제시(Jessi),7.0,bugs,6.5
7,bugs,감동이야 (feat. 성시경),싸이 (PSY),2.0,bugs,5.6
8,bugs,나의 X에게,경서,7.5,bugs,9.0
9,bugs,밤이 깊었네 (feat. 헤이즈),싸이 (PSY),5.0,bugs,8.0
10,bugs,봄 to 러브,10CM,3.5,bugs,3.0
11,bugs,봄여름가을겨울 (Still Life),BIGBANG (빅뱅),4.6,bugs,5.0
12,bugs,사랑인가 봐,멜로망스(MeloMance),8.8,bugs,6.0
13,bugs,이제는 (feat. 화사),싸이 (PSY),7.0,bugs,6.5

In [47]:
bvsc_df = bvsc_df.drop('사이트_y', axis=1)
bvsc_df

,사이트_x,곡,가수,과거순위평균,현재순위평균
0,bugs,Celeb,싸이 (PSY),5.0,6.0
1,bugs,Feel My Rhythm,Red Velvet (레드벨벳),7.5,7.6
2,bugs,LOVE DIVE,IVE (아이브),2.3,3.0
3,bugs,Seoul,볼빨간사춘기,6.6,8.2
4,bugs,TOMBOY,(여자)아이들,6.4,5.4
5,bugs,That That (prod. & feat. SUGA of BTS),싸이 (PSY),1.0,1.0
6,bugs,ZOOM,제시(Jessi),7.0,6.5
7,bugs,감동이야 (feat. 성시경),싸이 (PSY),2.0,5.6
8,bugs,나의 X에게,경서,7.5,9.0
9,bugs,밤이 깊었네 (feat. 헤이즈),싸이 (PSY),5.0,8.0
10,bugs,봄 to 러브,10CM,3.5,3.0
11,bugs,봄여름가을겨울 (Still Life),BIGBANG (빅뱅),4.6,5.0
12,bugs,사랑인가 봐,멜로망스(MeloMance),8.8,6.0
13,bugs,이제는 (feat. 화사),싸이 (PSY),7.0,6.5

In [48]:
bvsc_df['전주 대비 상승폭'] = bvsc_df['현재순위평균'] - bvsc_df['과거순위평균']
bvsc_df

,사이트_x,곡,가수,과거순위평균,현재순위평균,전주 대비 상승폭
0,bugs,Celeb,싸이 (PSY),5.0,6.0,1.0
1,bugs,Feel My Rhythm,Red Velvet (레드벨벳),7.5,7.6,0.1
2,bugs,LOVE DIVE,IVE (아이브),2.3,3.0,0.7
3,bugs,Seoul,볼빨간사춘기,6.6,8.2,1.6
4,bugs,TOMBOY,(여자)아이들,6.4,5.4,-1.0
5,bugs,That That (prod. & feat. SUGA of BTS),싸이 (PSY),1.0,1.0,0.0
6,bugs,ZOOM,제시(Jessi),7.0,6.5,-0.5
7,bugs,감동이야 (feat. 성시경),싸이 (PSY),2.0,5.6,3.6
8,bugs,나의 X에게,경서,7.5,9.0,1.5
9,bugs,밤이 깊었네 (feat. 헤이즈),싸이 (PSY),5.0,8.0,3.0
10,bugs,봄 to 러브,10CM,3.5,3.0,-0.5
11,bugs,봄여름가을겨울 (Still Life),BIGBANG (빅뱅),4.6,5.0,0.4
12,bugs,사랑인가 봐,멜로망스(MeloMance),8.8,6.0,-2.8
13,bugs,이제는 (feat. 화사),싸이 (PSY),7.0,6.5,-0.5

### 파일 저장

In [ ]:
# 파일 저장
save_folder = f'/crawled_data/outlier_data/{new_start_date}_{new_end_date}/{site_name}/'
path = code_path + save_folder
file_name = f'[{site_name}]{new_start_date}_{new_end_date}_Top10_rank_change_df.xlsx'
bvsc_df.to_excel(path + file_name, index=False, encoding='utf-8')
print(f'{file_name} 출력완료.')

# 코드 마지막